# fly.toml app configuration file generated for horror-movie-club on 2025-05-09T14:18:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'horror-movie-club'
primary_region = 'iad'

[build]

[processes]
app = "python main.py"

[deploy]
release_command = ""

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1